### ISSUE TITLE
Unneeded variable in for loop

### ISSUE THREAD

**Issue by frenzymadness** [petracihalova/AM-dashboard#33]
If you don't need the keys, you can just use `.values()` instead `.items()`, I believe.

https://github.com/petracihalova/AM-dashboard/blob/208c9ac9097b60c9e90487403e281c2f4f6c040d/application/routes.py#L64

**Comment by frenzymadness** [comment]
The same here

https://github.com/petracihalova/AM-dashboard/blob/208c9ac9097b60c9e90487403e281c2f4f6c040d/application/routes.py#L89

**Comment by petracihalova** [comment]
first fixed here https://github.com/petracihalova/AM-dashboard/pull/64
second is not present in the code - was probably fixed earlier
