### ISSUE TITLE
No need for explicit `continue` if the list is empty

### ISSUE THREAD

**Issue by frenzymadness** [petracihalova/AM-dashboard#35]
I'm talking about:

https://github.com/petracihalova/AM-dashboard/blob/208c9ac9097b60c9e90487403e281c2f4f6c040d/application/routes.py#L38

If the list is empty and therefore `bool(list_of_pr) == False` the for loop would run 0 times anyway so you can remove the condition and the `continue` and just left the for loops there.

**Comment by petracihalova** [comment]
this is not present in the code - was probably fixed earlier
